name: dbt_Pipeline_Run

on:
  # Trigger on commits to main or dbt/** branches
  push:
    branches:
      - main
      - 'dbt/**'
    paths:
      - 'data_modelling/models/**'
      - 'data_modelling/macros/**'
      - 'data_modelling/tests/**'
      - 'data_modelling/dbt_project.yml'
      
  # push:
  #   branches:
  #     - main
  #     - 'dbt/**'
  #   paths:
  #     - 'data_modelling/models/**'
  #     - 'data_modelling/macros/**'
  #     - 'data_modelling/tests/**'
  #     - 'data_modelling/dbt_project.yml'

  # Trigger on pull requests to main
 # pull_request:
 #   branches:
 #     - main
 #   paths:
 #     - 'data_modelling/models/**'
 #     - 'data_modelling/macros/**'
 #     - 'data_modelling/tests/**'
 #     - 'data_modelling/dbt_project.yml'

  # Manual trigger
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow triggered on $GITHUB_EVENT_NAME"

  build:
    name: Run dbt Full Fresh Build
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DBNAME: ${{ secrets.DB_DBNAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres

#      - name: Check DB_PASSWORD exists
#        run: |
#          if [ -z "$DB_PASSWORD" ]; then
#            echo "DB_PASSWORD is EMPTY ❌"
#            exit 1
#          else
#            echo "DB_PASSWORD is set ✅"
#          fi

      - name: Compile dbt project
        run: dbt compile --profiles-dir . --target dev
        working-directory: ./data_modelling

      - name: Drop all dbt models from dev schema
        run: dbt run-operation drop_all --profiles-dir . --target dev
        working-directory: ./data_modelling

      - name: Clean local dbt artifacts
        run: dbt clean --profiles-dir . --target dev
        working-directory: ./data_modelling

      - name: Install dbt dependencies
        run: dbt deps --profiles-dir . --target dev
        working-directory: ./data_modelling

      - name: Build all dbt models
        run: dbt build --profiles-dir . --target dev
        working-directory: ./data_modelling
