name: Pipline_Run

on:
  push:
    branches:
      - main
      - 'feature/dbt/**'
    paths:
      - 'data_modelling/models/**'
      - 'data_modelling/macros/**'
      - 'data_modelling/tests/**'
      - 'data_modelling/dbt_project.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'data_modelling/models/**'
      - 'data_modelling/macros/**'
      - 'data_modelling/tests/**'
      - 'data_modelling/dbt_project.yml'

  workflow_dispatch:

concurrency:
  group: dbt-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Run dbt Data Quality Checks
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_DBNAME: ${{ secrets.DB_DBNAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres

      - name: dbt clean
        run: dbt clean --profiles-dir . --target dev
        working-directory: ./data_modelling

      - name: dbt deps
        run: dbt deps --profiles-dir . --target dev
        working-directory: ./data_modelling

      # -----------------------------
      # PR = Slim CI (modified models)
      # -----------------------------
      - name: Save dbt state (main branch)
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin main:main
          dbt compile --profiles-dir . --target dev --state ./ --defer
        working-directory: ./data_modelling

      - name: dbt build (PR slim CI)
        if: github.event_name == 'pull_request'
        run: |
          dbt build --profiles-dir . --target dev --select state:modified+ --defer --state .
        working-directory: ./data_modelling

      # -----------------------------
      # Push to main = Full build
      # -----------------------------
      - name: dbt build (main full build)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          dbt build --profiles-dir . --target dev
        working-directory: ./data_modelling
